### ISSUE TITLE
Bandit 1.7.3 breaks flake8-bandit 2.1.2

### ISSUE THREAD

**Issue by darless** [tylerwince/flake8-bandit#24]
The latest release for bandit broke flake8-bandit. I'll file a bug in flake8-bandit as well, but the core issue is with bandit. With the latest version there is an error that is displayed when trying to run flake8-bandit:

docker python:3.9

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/flake8/__main__.py", line 4, in <module>
    cli.main()
  File "/usr/local/lib/python3.9/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/usr/local/lib/python3.9/site-packages/flake8/main/application.py", line 360, in run
    self._run(argv)
  File "/usr/local/lib/python3.9/site-packages/flake8/main/application.py", line 348, in _run
    self.run_checks()
  File "/usr/local/lib/python3.9/site-packages/flake8/main/application.py", line 262, in run_checks
    self.file_checker_manager.run()
  File "/usr/local/lib/python3.9/site-packages/flake8/checker.py", line 325, in run
    self.run_serial()
  File "/usr/local/lib/python3.9/site-packages/flake8/checker.py", line 309, in run_serial
    checker.run_checks()
  File "/usr/local/lib/python3.9/site-packages/flake8/checker.py", line 589, in run_checks
    self.run_ast_checks()
  File "/usr/local/lib/python3.9/site-packages/flake8/checker.py", line 496, in run_ast_checks
    for (line_number, offset, text, _) in runner:
  File "/usr/local/lib/python3.9/site-packages/flake8_bandit.py", line 80, in run
    for warn in self._check_source():
  File "/usr/local/lib/python3.9/site-packages/flake8_bandit.py", line 54, in _check_source
    bnv = BanditNodeVisitor(
TypeError: __init__() missing 1 required positional argument: 'metrics'
```

### Workaround
```
pip install flake8-bandit==2.1.2 bandit==1.7.2
```

### Reproduction steps
1. docker run -it python:3.9 bash
2. pip install flake8-bandit==2.1.2
3. touch test.py
4. python -m flake8 test.py

The same issue if using python:3.7
Expected behavior
No output with a blank python file

### Bandit version
`1.7.3 (Default)`

### Python version
3.9

### Link to Bandit issue
https://github.com/PyCQA/bandit/issues/837

**Comment by Katolus** [comment]
If you don't mind me asking, why is this not an issue anymore?

**Comment by darless** [comment]
I just tested against the latest flake8-bandit and the error has gone away.

Old versions have the issue present

```
docker run -it python:3.9 bash
pip3 install flake8==3.9.2 flake8-bandit==2.1.2 bandit==1.7.3
```

With the testing, the local directory has a python file to test with.

The metrics error will be seen
```
python3 -m flake8 --select S .
```

However, running with the latest versions the error is not present
```
pip3 install flake8-bandit
```

freeze output for the main packages
```
root@49ae5b542a8d:/# pip3 freeze | grep "flake8\|bandit"
bandit==1.7.4
flake8==6.0.0
flake8-bandit==4.1.1
```

No error output was seen with these versions:
```
root@6cc613ad8d1a:/app# python3 -m flake8 --select S .
```
