### ISSUE TITLE
Crashes with flake8 5

### ISSUE THREAD

**Issue by languitar** [tylerwince/flake8-bandit#37]
```
 Traceback (most recent call last):
  File "/home/runner/work/autosuspend/autosuspend/.tox/check/lib/python3.9/site-packages/flake8/plugins/finder.py", line 296, in _load_plugin
    obj = plugin.entry_point.load()
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/runner/work/autosuspend/autosuspend/.tox/check/lib/python3.9/site-packages/flake8_bandit.py", line 10, in <module>
    from flake8.options.config import ConfigFileFinder
ImportError: cannot import name 'ConfigFileFinder' from 'flake8.options.config' (/home/runner/work/autosuspend/autosuspend/.tox/check/lib/python3.9/site-packages/flake8/options/config.py)
```

**Comment by konstruktoid** [comment]
See https://github.com/tylerwince/flake8-bandit/issues/33

**Comment by languitar** [comment]
Oh, I've missed that because flake version 5 is not in the summary.
